language: c

sudo: false

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/flux-core
    - $HOME/local
    - $HOME/.luarocks
    - $HOME/.ccache

addons:
  apt:
    sources:
    packages:
      - lua5.1
      - liblua5.1-0-dev
      - luarocks
      - uuid-dev
      - aspell
      - libopenmpi-dev
      - ccache
      - libmunge-dev
      - munge

before_install:
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - export CPPFLAGS=-I$HOME/local/include
  - export LDFLAGS=-L$HOME/local/lib
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig
  - test "$TRAVIS_PULL_REQUEST" == "false" || export CCACHE_READONLY=1
  - if test "$CC" = "clang"; then export CCACHE_CPP2=1; fi
  - eval `luarocks path`
  - wget https://raw.githubusercontent.com/flux-framework/flux-core/master/src/test/travis-dep-builder.sh
  - bash ./travis-dep-builder.sh --cachedir=$HOME/local/.cache


script:
 - export CC="ccache $CC"
 - test -d  $HOME/flux-core/.git || git clone https://github.com/flux-framework/flux-core $HOME/flux-core
 - (cd $HOME/flux-core && git pull && ./autogen.sh && ./configure && make -j 2)
 - (cd $HOME/flux-core/src/common/libtap && make check)
 - ./config $HOME/flux-core && make check


